Repository dcastil/tailwind-merge, pull requests merged in 2023-08, with the labels that each got.

#284 Rename lazy-initializaton.test.ts to lazy-initialization.test.ts
  tests/lazy-initialization.test.ts
Labels: bugfix

#286 Add ES5 bundle
  .github/workflows/codeql-analysis.yml
  .github/workflows/npm-publish-dev.yml
  .github/workflows/npm-publish.yml
  .github/workflows/size.yml
  .github/workflows/test.yml
  .size-limit.json
  package.json
  scripts/jest.config.mjs
  scripts/rollup.config.mjs
  scripts/test-built-package-exports.mjs
  tsconfig.json
  yarn.lock
Labels: feature

#287 Transpile lib to more modern JS
  scripts/rollup.config.mjs
  tsconfig.json
Labels: feature, breaking

#288 Remove deprecated exports
  src/index.ts
  src/lib/validators.ts
  tests/public-api.test.ts
Labels: feature, breaking

#289 Remove `module` field from package.json
  package.json
Labels: feature, breaking

#290 Move separator to config
  src/lib/default-config.ts
  src/lib/modifier-utils.ts
  src/lib/types.ts
  tests/create-tailwind-merge.test.ts
  tests/merge-configs.test.ts
  tests/modifiers.test.ts
  tests/public-api.test.ts
Labels: feature, breaking

#291 Make `conflictingClassGroupModifiers` in config non-optional
  src/lib/types.ts
  tests/create-tailwind-merge.test.ts
  tests/merge-configs.test.ts
  tests/public-api.test.ts
Labels: feature, breaking

#292 Separate validators better
  docs/api-reference.md
  src/lib/default-config.ts
  src/lib/validators.ts
  tests/validators.test.ts
Labels: feature, breaking

#294 Make it possible to override elements with `extendTailwindMerge`
  docs/api-reference.md
  docs/configuration.md
  docs/recipes.md
  docs/writing-plugins.md
  src/lib/extend-tailwind-merge.ts
  src/lib/merge-configs.ts
  src/lib/types.ts
  tests/extend-tailwind-merge.test.ts
  tests/merge-configs.test.ts
  tests/theme.test.ts
Labels: feature, breaking

#295 Fix number validators accidentally returning `true` for empty strings
  src/lib/validators.ts
Labels: bugfix

#299 Add changelog and migration guide for v2
  docs/api-reference.md
  docs/changelog/v0-changelog.md
  docs/changelog/v0-to-v1-migration.md
  docs/changelog/v1-changelog.md
  docs/changelog/v1-to-v2-migration.md
  src/lib/class-utils.ts
Labels: documentation

#300 Fix `background-image` and `background-position` being merged incorrectly
  docs/api-reference.md
  docs/changelog/v1-to-v2-migration.md
  src/lib/default-config.ts
  src/lib/validators.ts
  tests/arbitrary-values.test.ts
  tests/public-api.test.ts
  tests/validators.test.ts
Labels: bugfix, breaking, needs changelog edit
