Repository dcastil/tailwind-merge, pull requests merged in 2023-11, with the labels that each got.

#347 Fix display class not removed when it precedes line-clamp class
  src/lib/default-config.ts
  tests/conflicts-across-class-groups.test.ts
Labels: bugfix

#348 Add `ClassValidator` type to package exports
  docs/api-reference.md
  src/index.ts
  tests/public-api.test.ts
Labels: feature, context-v2

#349 chore(docs): remove extra curly bracket
  docs/configuration.md
Labels: documentation, context-v2
