Repository dcastil/tailwind-merge, pull requests merged in 2024-06, with the labels that each got.

#431 Avoid `@babel/runtime` dependency
  package.json
  scripts/rollup.config.mjs
  yarn.lock
Labels: feature

#433 Replace size-limit action with own metrics-report action
  .github/actions/metrics-report/.gitignore
  .github/actions/metrics-report/action.yml
  .github/actions/metrics-report/package.json
  .github/actions/metrics-report/src/get-package-size.mjs
  .github/actions/metrics-report/src/get-size-metrics-report-content.mjs
  .github/actions/metrics-report/src/main.mjs
  .github/actions/metrics-report/src/set-comment.mjs
  .github/actions/metrics-report/src/utils/git.mjs
  .github/actions/metrics-report/src/utils/github.mjs
  .github/actions/metrics-report/src/utils/html.mjs
  .github/actions/metrics-report/src/utils/path.mjs
  .github/actions/metrics-report/yarn.lock
  .github/workflows/metrics-report.yml
  .github/workflows/npm-publish-dev.yml
  .github/workflows/npm-publish.yml
  .github/workflows/size.yml
  .size-limit.json
  package.json
  scripts/rollup.config.mjs
  yarn.lock
Labels: other, skip changelog

#434 Added GitHub Action that adds context-v2 label everywhere
  .github/workflows/label.yml
Labels: other

#439 Create security policy
  .github/SECURITY.md
Labels: feature, context-v2
