Repository dcastil/tailwind-merge, pull requests merged in 2024-08, with the labels that each got.

#457 Fx space at beginning of input causing infinite loop
  src/lib/merge-classlist.ts
  tests/wonky-inputs.test.ts
Labels: bugfix, context-v2

#459 Fix multiline input not working anymore
  src/lib/merge-classlist.ts
  tests/wonky-inputs.test.ts
Labels: bugfix, context-v2

#455 Implemented benchmarks
  .github/workflows/benchmarks.yml
  benchmarks/perf-test-data.json
  benchmarks/twMerge.bench.ts
  package.json
  vitest.config.mts
  yarn.lock
Labels: documentation, context-v2

#461 Switch test suite to vitest
  .eslintrc.json
  .github/workflows/benchmarks.yml
  .github/workflows/npm-publish.yml
  .github/workflows/test.yml
  benchmarks/twMerge.bench.ts
  package.json
  scripts/jest.config.mjs
  scripts/rollup.config.mjs
  scripts/vitest.config.mts
  tests/arbitrary-properties.test.ts
  tests/arbitrary-values.test.ts
  tests/arbitrary-variants.test.ts
  tests/class-group-conflicts.test.ts
  tests/class-map.test.ts
  tests/colors.test.ts
  tests/conflicts-across-class-groups.test.ts
  tests/content-utilities.test.ts
  tests/create-tailwind-merge.test.ts
  tests/default-config.test.ts
  tests/docs-examples.test.ts
  tests/experimental-parse-class-name.test.ts
  tests/extend-tailwind-merge.test.ts
  tests/important-modifier.test.ts
  tests/lazy-initialization.test.ts
  tests/merge-configs.test.ts
  tests/modifiers.test.ts
  tests/negative-values.test.ts
  tests/non-conflicting-classes.test.ts
  tests/non-tailwind-classes.test.ts
  tests/per-side-border-colors.test.ts
  tests/prefixes.test.ts
  tests/pseudo-variants.test.ts
  tests/public-api.test.ts
  tests/separators.test.ts
  tests/standalone-classes.test.ts
  tests/tailwind-css-versions.test.ts
  tests/theme.test.ts
  tests/tsconfig.json
  tests/tw-join.test.ts
  tests/tw-merge-benchmark-data.json
  tests/tw-merge.benchmark.ts
  tests/tw-merge.test.ts
  tests/type-generics.test.ts
  tests/validators.test.ts
  tests/wonky-inputs.test.ts
  vitest.config.mts
  yarn.lock
Labels: other, context-v2
