Repository dcastil/tailwind-merge, pull requests merged in 2024-07, with the labels that each got.

#443 Comment/typo fixes
  docs/configuration.md
  src/lib/types.ts
Labels: context-v2

#444 Allow hooking into class parsing logic (experimental)
  docs/versioning.md
  src/index.ts
  src/lib/class-group-utils.ts
  src/lib/config-utils.ts
  src/lib/merge-classlist.ts
  src/lib/merge-configs.ts
  src/lib/parse-class-name.ts
  src/lib/types.ts
  tests/class-map.test.ts
  tests/experimental-parse-class-name.test.ts
Labels: feature, context-v2

#449 Use arrow functions where possible to help with minification
  src/lib/class-group-utils.ts
  src/lib/config-utils.ts
  src/lib/default-config.ts
  src/lib/extend-tailwind-merge.ts
  src/lib/from-theme.ts
  src/lib/lru-cache.ts
  src/lib/merge-classlist.ts
  src/lib/merge-configs.ts
  src/lib/parse-class-name.ts
  src/lib/tw-join.ts
  src/lib/validators.ts
Labels: feature, context-v2

#450 refactor(perf): reduce allocations overhead from mergeClassList
  src/lib/merge-classlist.ts
Labels: feature, context-v2

#451 Fix bg-opacity arbitrary percentages not being recognized properly
  src/lib/default-config.ts
  tests/arbitrary-properties.test.ts
Labels: bugfix, context-v2
