Repository dcastil/tailwind-merge, pull requests merged in 2025-03, with the labels that each got.

#545 Update shadow scale recipe to tailwind merge v3 API
  .tool-versions
  docs/recipes.md
Labels: bug, context-v3

#546 Add support for Tailwind CSS v4.0.10
  src/lib/default-config.ts
  tests/tailwind-css-versions.test.ts
Labels: feature, context-v3

#549 Fix typo in comment in types.ts
  src/lib/types.ts
Labels: documentation, context-v3

#551 Fix metrics report action erroring on PRs from forks
  .github/actions/metrics-report/package.json
  .github/actions/metrics-report/src/main.mjs
  .github/actions/metrics-report/yarn.lock
Labels: other, context-v3

#559 Fix length variable in `via-(length:*)` class being merged with `via-<color>` classes accidentally
  src/lib/default-config.ts
  tests/tailwind-css-versions.test.ts
Labels: bug, context-v3
